/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.PatientRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.DoctorOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.RequestDoctorWorkRequest;
import java.awt.CardLayout;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.apache.log4j.Logger;

    
/**
 *
 * @author Gauri
 */
public class RequestDoctorJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount patientAccount;
    private EcoSystem system;
    
    private static final Logger logger =Logger.getLogger(RequestDoctorJPanel.class);
    /**
     * Creates new form RequestDoctorJPanel
     */
    public RequestDoctorJPanel(JPanel userProcessContainer,UserAccount userAccount,Enterprise enterprise,EcoSystem system) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.patientAccount=userAccount;
        this.enterprise=enterprise;
        this.system=system;
        
        populateReasonForVisitJComboBox();
    }

    public void populateReasonForVisitJComboBox(){
        reasonForVisitJComboBox.removeAllItems();
        
        reasonForVisitJComboBox.addItem("Skin disorders");
        reasonForVisitJComboBox.addItem("Osteoarthritis and joint disorders");
        reasonForVisitJComboBox.addItem("Back problems");
        reasonForVisitJComboBox.addItem("Cholesterol problems");
        reasonForVisitJComboBox.addItem("Upper respiratory conditions");
        reasonForVisitJComboBox.addItem("Headaches and migraines");
        reasonForVisitJComboBox.addItem("Anxiety, bipolar disorder and depression");
        reasonForVisitJComboBox.addItem("Chronic neurologic disorders");
        reasonForVisitJComboBox.addItem("High blood pressure");
        reasonForVisitJComboBox.addItem("Diabetes");
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRequestDoctor = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        reasonForVisitJComboBox = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRequestDoctor.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnRequestDoctor.setText("Request Doctor");
        btnRequestDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestDoctorActionPerformed(evt);
            }
        });
        add(btnRequestDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, -1, 50));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel2.setText("Reason for Visit");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 149, -1, -1));

        btnBack.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, -1, -1));

        reasonForVisitJComboBox.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        reasonForVisitJComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(reasonForVisitJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 146, 204, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setText("Request Doctor");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/4.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnRequestDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestDoctorActionPerformed
        // TODO add your handling code here:
        String requestReason = (String) reasonForVisitJComboBox.getSelectedItem();
        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
        Date date = new Date();
        
        RequestDoctorWorkRequest request = new RequestDoctorWorkRequest();
        request.setWorkRequestId(system.getIv().getWorkRequestId());
        request.setSender(patientAccount);
        request.setProblem(requestReason);
        request.setStatus("Sent");
        request.setRequestDate(date);
        
        
        Organization org=null;
        for(Organization organization:enterprise.getOrganizationDirectory().getOrganizationList()){
            if(organization instanceof DoctorOrganization){
                org=organization;
                break;
            }
        }
        if(org!=null){
                org.getWorkQueue().getWorkRequestList().add(request);
                patientAccount.getWorkQueue().getWorkRequestList().add(request);
                logger.info(patientAccount.getUserName()+" Requested for Doctor for reason : "+requestReason);
                JOptionPane.showMessageDialog(null, "Requested for a Doctor", "Information", JOptionPane.INFORMATION_MESSAGE);
                
        }
        if(org == null){
            logger.info(patientAccount.getUserName()+" Requested for Doctor but Doctor Organization not available !");
            JOptionPane.showMessageDialog(null, "First Create Doctor Organization", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_btnRequestDoctorActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRequestDoctor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox<String> reasonForVisitJComboBox;
    // End of variables declaration//GEN-END:variables
}
