/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.LabRole;

import Business.Checks.CheckString;
import Business.Enterprise.Enterprise;
import Business.Patient.Patient;
import Business.Patient.VitalSign;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.PerformTestWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.apache.log4j.Logger;

/**
 *
 * @author Gauri
 */
public class ConductTestJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private PerformTestWorkRequest request;
    
    private static final Logger logger =Logger.getLogger(ConductTestJPanel.class);
    /**
     * Creates new form ConductTestJPanel
     */
    public ConductTestJPanel(JPanel userProcessContainer,Enterprise enterprise,UserAccount userAccount,PerformTestWorkRequest request) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        this.request = request;
        
        submitButtonFunctionality();
        
        Patient p = (Patient) request.getPatientAccount().getPerson();
        txtPatientId.setText(String.valueOf(p.getId()));
        txtPatientName.setText(p.getFirstName()+" "+p.getLastName());
    }
    
    public void submitButtonFunctionality(){
        if(request.getStatus().equals("Pending")){
            btnSubmit.setEnabled(true);
        }
        else{
            btnSubmit.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtPatientId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPatientName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtRespiratoryRate = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtHeartRate = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtBloodPressure = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtWeight = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel2.setText("Patient Id");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 102, 156, 29));

        txtPatientId.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        txtPatientId.setEnabled(false);
        txtPatientId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPatientIdActionPerformed(evt);
            }
        });
        add(txtPatientId, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 102, 156, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel3.setText("Patient Name");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 143, 156, 29));

        txtPatientName.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        txtPatientName.setEnabled(false);
        txtPatientName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPatientNameActionPerformed(evt);
            }
        });
        add(txtPatientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 143, 156, -1));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel4.setText("Respiratory Rate");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 219, 156, 29));

        txtRespiratoryRate.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        txtRespiratoryRate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRespiratoryRateActionPerformed(evt);
            }
        });
        add(txtRespiratoryRate, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 219, 156, -1));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel5.setText("Heart Rate");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 266, 156, 29));

        txtHeartRate.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        txtHeartRate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHeartRateActionPerformed(evt);
            }
        });
        add(txtHeartRate, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 266, 156, -1));

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel6.setText("Blood Pressure");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 313, 156, 29));

        txtBloodPressure.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        txtBloodPressure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBloodPressureActionPerformed(evt);
            }
        });
        add(txtBloodPressure, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 313, 156, -1));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel7.setText("Weight");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 360, 156, 29));

        txtWeight.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        txtWeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWeightActionPerformed(evt);
            }
        });
        add(txtWeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 360, 156, -1));

        btnSubmit.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 420, 130, 50));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setText("Conduct Test");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, -1, -1));

        btnBack.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 110, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/4.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtPatientIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPatientIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPatientIdActionPerformed

    private void txtPatientNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPatientNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPatientNameActionPerformed

    private void txtRespiratoryRateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRespiratoryRateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRespiratoryRateActionPerformed

    private void txtHeartRateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHeartRateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHeartRateActionPerformed

    private void txtBloodPressureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBloodPressureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBloodPressureActionPerformed

    private void txtWeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWeightActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        
        try{
            int respiratoryRate = Integer.parseInt(txtRespiratoryRate.getText().trim());
            int heartRate = Integer.parseInt(txtHeartRate.getText().trim());
            int bloodPressure = Integer.parseInt(txtBloodPressure.getText().trim());
            int weight = Integer.parseInt(txtWeight.getText().trim());

            DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
            Date date = new Date();

            Boolean checkRespiratoryRate = CheckString.DoubleValidation((double)respiratoryRate);
            Boolean checkHeartRate = CheckString.DoubleValidation((double)heartRate);
            Boolean checkBloodPressure = CheckString.DoubleValidation((double)bloodPressure);
            Boolean checkWeight = CheckString.DoubleValidation((double)weight);

            if(checkRespiratoryRate==true && checkHeartRate==true && checkBloodPressure==true && checkWeight==true){
                Patient p = (Patient) request.getPatientAccount().getPerson();
                VitalSign vitalSign = p.getVitalSignHistory().createAndAddVitalSign();
                vitalSign.setRespiratoryRate(respiratoryRate);
                vitalSign.setHeartRate(heartRate);
                vitalSign.setBloodPressure(bloodPressure);
                vitalSign.setWeight(weight);
                vitalSign.setTimestamp(date);

                request.setRespiratoryRate(respiratoryRate);
                request.setHeartRate(heartRate);
                request.setBloodPressure(bloodPressure);
                request.setWeight(weight);
                request.setTimestamp(date);
                request.setStatus("Test Conducted");

                btnSubmit.setEnabled(false);
                JOptionPane.showMessageDialog(null, "Test Completed and sent to Doctor", "Information", JOptionPane.INFORMATION_MESSAGE);
                logger.info("Test Completed by "+ userAccount.getUserName()+" and Sent to Doctor ");
            }
        }
        
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Enter correct data", "Warning", JOptionPane.WARNING_MESSAGE);
            
        }
        
        
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        LabWorkAreaJPanel lab = (LabWorkAreaJPanel) component;
        lab.populatePerformTest();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtBloodPressure;
    private javax.swing.JTextField txtHeartRate;
    private javax.swing.JTextField txtPatientId;
    private javax.swing.JTextField txtPatientName;
    private javax.swing.JTextField txtRespiratoryRate;
    private javax.swing.JTextField txtWeight;
    // End of variables declaration//GEN-END:variables
}
