/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
*/
package UserInterface.Tier1Analyst;

import Business.Enterprise.Enterprise;
import Business.Organization.SecurityOrganization;
import Business.Person.Person;
import Business.Role.Role;
import Business.Role.Role.RoleType;
import Business.Role.Tier2AnalystRole;
import Business.Security.Tier1Analyst;
import Business.Security.Tier2Analyst;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.UnusualActivityWorkRequest;
import Business.WorkQueue.WorkRequest;
import UserInterface.ReceptionistRole.ViewProfileJPanel;
import java.awt.CardLayout;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.apache.log4j.Logger;

/**
 *
 * @author Gauri
 */
public class Tier1WorkAreaJPanel extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private SecurityOrganization securityOrganization;
    private Enterprise enterprise;
    
    private static final Logger logger =Logger.getLogger(Tier1WorkAreaJPanel.class);
    /**
     * Creates new form Tier1WorkAreaJPanel
     */
    public Tier1WorkAreaJPanel(JPanel userProcessContainer, UserAccount account, SecurityOrganization securityOrganization, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.userAccount=account;
        this.securityOrganization=securityOrganization;
        this.enterprise=enterprise;
        
        // populateSecurityThreatTable();
        populateSecurityThreatsTable();
    }
    
    
    public void populateSecurityThreatTable(){
        DefaultTableModel dtm = (DefaultTableModel) tblSecutiryThreats.getModel();
        dtm.setRowCount(0);
        
        Tier1Analyst t1 = (Tier1Analyst) userAccount.getPerson();
        for(WorkRequest work:t1.getWorkQueue().getWorkRequestList()){
            if(work instanceof UnusualActivityWorkRequest){
                
                Object row[]=new Object[5];
                row[0]=work;//.getWorkRequestId();
                row[1]=((UnusualActivityWorkRequest) work).getThreatUser().getPerson().getFirstName();   //work.getThreatUser().getPerson().getFirstName();
                row[2]=((UnusualActivityWorkRequest) work).getThreatUser().getPerson().getLastName();
                row[3]=work.getMessage();
                row[4]=work.getStatus();
                
                dtm.addRow(row);
            }
        }
    }
    
    public void populateSecurityThreatsTable(){
        DefaultTableModel dtm = (DefaultTableModel) tblSecutiryThreats.getModel();
        dtm.setRowCount(0);
        
        for(WorkRequest work : securityOrganization.getWorkQueue().getWorkRequestList()){
            
            if(work instanceof UnusualActivityWorkRequest){
                
                Object row[]=new Object[5];
                row[0]=work;//.getWorkRequestId();
                row[1]=((UnusualActivityWorkRequest) work).getThreatUser().getPerson().getFirstName();   //work.getThreatUser().getPerson().getFirstName();
                row[2]=((UnusualActivityWorkRequest) work).getThreatUser().getPerson().getLastName();
                row[3]=work.getMessage();
                row[4]=work.getStatus();
                
                dtm.addRow(row);
            }
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnViewLog = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSecutiryThreats = new javax.swing.JTable();
        btnViewRequest = new javax.swing.JButton();
        btnEscalateRequests = new javax.swing.JButton();
        btnResolveThreat = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        btnViewProfile = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnViewLog.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnViewLog.setText("View Log");
        btnViewLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewLogActionPerformed(evt);
            }
        });
        add(btnViewLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 304, 158, 54));

        tblSecutiryThreats.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        tblSecutiryThreats.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Work Request id", "First Name", "Last Name", "Message", "Status"
            }
        ));
        jScrollPane1.setViewportView(tblSecutiryThreats);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 590, 179));

        btnViewRequest.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnViewRequest.setText("View Request");
        btnViewRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewRequestActionPerformed(evt);
            }
        });
        add(btnViewRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(454, 304, 158, 54));

        btnEscalateRequests.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnEscalateRequests.setText("Escalate Request");
        btnEscalateRequests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEscalateRequestsActionPerformed(evt);
            }
        });
        add(btnEscalateRequests, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, 158, 54));

        btnResolveThreat.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnResolveThreat.setText("Resolve Threat");
        btnResolveThreat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResolveThreatActionPerformed(evt);
            }
        });
        add(btnResolveThreat, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 390, 170, 54));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setText("Tier 1 Analyst Work Area");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, -1, -1));

        btnViewProfile.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnViewProfile.setText("View Profile");
        btnViewProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewProfileActionPerformed(evt);
            }
        });
        add(btnViewProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 469, 155, 60));

        jButton1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jButton1.setText("Activate User Account");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 470, 170, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/4.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewLogActionPerformed
        // TODO add your handling code here:
        if (Desktop.isDesktopSupported()) {
            try {
                File myFile = new File("/Users/Gauri/NetBeansProjects/AEDFinalProject/log/example.log");
                Desktop.getDesktop().open(myFile);
            } catch (IOException ex) {
              //  System.out.println("Could not opendddfd");
                // no application registered for PDFs
            }
        }
    }//GEN-LAST:event_btnViewLogActionPerformed

    private void btnViewRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewRequestActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblSecutiryThreats.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null, "Select a Row !", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        WorkRequest workRequest = (UnusualActivityWorkRequest) tblSecutiryThreats.getValueAt(selectedRow, 0);
        if(workRequest.getStatus().equals("Sent")){
            ViewSecurityThreatJPanel viewSecurityThreatJPanel = new ViewSecurityThreatJPanel(userProcessContainer, (UnusualActivityWorkRequest) workRequest,userAccount);
            userProcessContainer.add("viewSecurityThreatJPanel",viewSecurityThreatJPanel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
        else if(workRequest.getStatus().equals("Request Escalated")){
            JOptionPane.showMessageDialog(null, "Request has been Already been Escalated !", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        
        else{
            JOptionPane.showMessageDialog(null, "Request Already Under Review !", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        
        
    }//GEN-LAST:event_btnViewRequestActionPerformed

    private void btnEscalateRequestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEscalateRequestsActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblSecutiryThreats.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null, "First Select a Request !", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        WorkRequest request = (UnusualActivityWorkRequest) tblSecutiryThreats.getValueAt(selectedRow, 0);
        
        
        if(!request.getStatus().equals("Request Escalated")){
            Boolean tier2AnalystExist=false;
            if(request.getStatus().equals("Reviewed")){
                for(UserAccount ua:securityOrganization.getUserAccountDirectory().getUserAccountList()){
                    if(String.valueOf(ua.getRole()).equals(RoleType.Tier2Analyst.getValue())){
                        ua.getWorkQueue().getWorkRequestList().add(request);
                        tier2AnalystExist=true;
                        break;
                    }
                }
                if(tier2AnalystExist==true){
                    request.setStatus("Request Escalated");
                    populateSecurityThreatsTable();
                    JOptionPane.showMessageDialog(null, "Work Request Escalated to Tier 2 !", "Information", JOptionPane.INFORMATION_MESSAGE);
                }
                else{
                    JOptionPane.showMessageDialog(null, "Tier2 Analysts do not Exist !", "Warning", JOptionPane.WARNING_MESSAGE);
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "First Set the Severity !", "Warning", JOptionPane.WARNING_MESSAGE);
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Request has been Already been Escalated !", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        
        
        
    }//GEN-LAST:event_btnEscalateRequestsActionPerformed

    private void btnResolveThreatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResolveThreatActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblSecutiryThreats.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null, "First Select a Request !", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        UnusualActivityWorkRequest request = (UnusualActivityWorkRequest) tblSecutiryThreats.getValueAt(selectedRow, 0);
        
        Boolean checkSOCAnalysisExist=false;
        if(request.getStatus().equals("Reviewed")){
            if(request.getSeverity()<2 ){
                for(UserAccount ua:securityOrganization.getUserAccountDirectory().getUserAccountList()){
                    if(String.valueOf(ua.getRole()).equals(RoleType.SOCAnalysisTeam.getValue())){
                        ua.getWorkQueue().getWorkRequestList().add(request);
                        checkSOCAnalysisExist=true;
                    }
                }
                if(checkSOCAnalysisExist==true){
                    JOptionPane.showMessageDialog(null, "Work Request Escalated to SOC Analysis Team !", "Information", JOptionPane.INFORMATION_MESSAGE);
                }
                else{
                    JOptionPane.showMessageDialog(null, "SOC Analysis Team do not Exist !", "Warning", JOptionPane.WARNING_MESSAGE);
                    return;
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "Escalate Work Request to Tier 2 Analyst", "Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }
            
        }
        else if(request.getStatus().equals("Request Escalated")){
            JOptionPane.showMessageDialog(null, "Request has been Already been Escalated !", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        
        else{
            JOptionPane.showMessageDialog(null, "Request is not under reciew !", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
    }//GEN-LAST:event_btnResolveThreatActionPerformed

    private void btnViewProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewProfileActionPerformed
        // TODO add your handling code here:
        logger.info(userAccount.getUserName()+" Viewed Profile");
        ViewProfileJPanel viewTier1AnalystProfileJPanel = new ViewProfileJPanel(userProcessContainer,enterprise,userAccount);
        userProcessContainer.add("viewTier1AnalystProfileJPanel",viewTier1AnalystProfileJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewProfileActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        EnableUserJPanel enableUser = new EnableUserJPanel(userProcessContainer,enterprise,userAccount);
        userProcessContainer.add("enableUser",enableUser);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEscalateRequests;
    private javax.swing.JButton btnResolveThreat;
    private javax.swing.JButton btnViewLog;
    private javax.swing.JButton btnViewProfile;
    private javax.swing.JButton btnViewRequest;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSecutiryThreats;
    // End of variables declaration//GEN-END:variables
}
