/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Tier1Analyst;

import Business.UserAccount.UserAccount;
import Business.WorkQueue.UnusualActivityWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.apache.log4j.Logger;

/**
 *
 * @author Gauri
 */
public class ViewSecurityThreatJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UnusualActivityWorkRequest workRequest;
    private UserAccount userAccount;
    
    private static final Logger logger =Logger.getLogger(ViewSecurityThreatJPanel.class);
    /**
     * Creates new form ViewSecurityThreatJPanel
     */
    public ViewSecurityThreatJPanel(JPanel userProcessContainer, UnusualActivityWorkRequest workRequest,UserAccount userAccount) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.workRequest=workRequest;
        this.userAccount=userAccount;
        
        completeTextFields();
        
    }
    
    public void completeTextFields(){
        txtWorkRequestId.setText(String.valueOf(workRequest.getWorkRequestId()));
        txtThreatUserName.setText(workRequest.getThreatUser().getUserName());
        txtMessage.setText(workRequest.getMessage());
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtWorkRequestId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtThreatUserName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtMessage = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        quantitySpinner = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setText("Work Request Id");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 113, 161, 29));

        txtWorkRequestId.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        txtWorkRequestId.setEnabled(false);
        add(txtWorkRequestId, new org.netbeans.lib.awtextra.AbsoluteConstraints(406, 113, 161, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel2.setText("Threat UserName");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 154, 161, 29));

        txtThreatUserName.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        txtThreatUserName.setEnabled(false);
        add(txtThreatUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(406, 154, 161, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel3.setText("Message");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 195, 161, 29));

        txtMessage.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        txtMessage.setEnabled(false);
        add(txtMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(406, 195, 161, -1));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel4.setText("Severity");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 236, 161, 29));

        btnSubmit.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 166, 49));

        btnBack.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setText("Security Threat Detail");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, -1, -1));

        quantitySpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        add(quantitySpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/4.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        workRequest.setStatus("Reviewed");
        workRequest.setReceiver(userAccount);
        workRequest.setSeverity((int) quantitySpinner.getValue());
        userAccount.getWorkQueue().getWorkRequestList().add(workRequest);
        
        JOptionPane.showMessageDialog(null, "Severity for Threat Assigned Successfully !", "Information", JOptionPane.INFORMATION_MESSAGE);
        btnSubmit.setEnabled(false);
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        Tier1WorkAreaJPanel tier1 = (Tier1WorkAreaJPanel) component;
        tier1.populateSecurityThreatsTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSpinner quantitySpinner;
    private javax.swing.JTextField txtMessage;
    private javax.swing.JTextField txtThreatUserName;
    private javax.swing.JTextField txtWorkRequestId;
    // End of variables declaration//GEN-END:variables
}
