/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SOCChiefRole;

import Business.Organization.SecurityOrganization;
import Business.Person.Person;
import Business.Role.Role;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.apache.log4j.Logger;

/**
 *
 * @author Gauri
 */
public class ViewSecurityEmployeesJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private SecurityOrganization securityOrganization;
    
    private static final Logger logger =Logger.getLogger(ViewSecurityEmployeesJPanel.class);
    /**
     * Creates new form ViewSecurityEmployeesJPanel
     */
    public ViewSecurityEmployeesJPanel(JPanel userProcessContainer,SecurityOrganization securityOrganization) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.securityOrganization = securityOrganization;
        
        populateSecurityEmployees();
        
        populateRoleJComboBox();
    }
    
    public void populateRoleJComboBox(){
        roleJComboBox.removeAllItems();
        for(Role role:securityOrganization.getSupportedRole()){
            roleJComboBox.addItem(role);
        }
    }
    
    public void populateSecurityEmployees(){
         DefaultTableModel dtm = (DefaultTableModel) tblSecurityEmployees.getModel();
         dtm.setRowCount(0);
         
         for(UserAccount ua :securityOrganization.getUserAccountDirectory().getUserAccountList()){
             Object row[]=new Object[3];
             row[0] = ua;
             row[1] = ua.getPerson().getLastName();
             row[2] = ua.getRole();
             
             dtm.addRow(row);
         }
    }
    
 /*   public void populateSecurityEmployees(){
        DefaultTableModel dtm = (DefaultTableModel) tblSecurityEmployees.getModel();
        dtm.setRowCount(0);
        
        for(Person ua:securityOrganization.getPersonDirectory().getPersonList()){
           // System.out.println("ua.getRole() "+ua.getRole());
          //  System.out.println("Role "+role);
            
                System.out.println("insideeee");
                
                Object row[] = new Object[3];
                row[0] = ua;
                row[1] = ua.getLastName();
          //      row[2] = ua.getRole();
                
                dtm.addRow(row);
            
        }
    }*/
    
    public void populateSecurityEmployeesTable(Role role){
        DefaultTableModel dtm = (DefaultTableModel) tblSecurityEmployees.getModel();
        dtm.setRowCount(0);
        
        for(UserAccount ua:securityOrganization.getUserAccountDirectory().getUserAccountList()){
            System.out.println("ua.getRole() "+ua.getRole());
            System.out.println("Role "+role);
            if(ua.getRole().equals(role)){
                System.out.println("insideeee");
                
                Object row[] = new Object[3];
                row[0] = ua;
                row[1] = ua.getPerson().getLastName();
                row[2] = ua.getRole();
                
                dtm.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        roleJComboBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSecurityEmployees = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();

        jLabel1.setText("Role");

        roleJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        roleJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roleJComboBoxActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel2.setText("View Security Employees");

        tblSecurityEmployees.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "First Name", "Last Name", "Role"
            }
        ));
        jScrollPane1.setViewportView(tblSecurityEmployees);

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(73, 73, 73)
                                .addComponent(roleJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack)))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel2)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roleJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                .addComponent(btnBack))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void roleJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roleJComboBoxActionPerformed
        // TODO add your handling code here:
        Role role = (Role) roleJComboBox.getSelectedItem();     
        if(role!=null){
          //  populateSecurityEmployeesTable(role);
        }
        
        
    }//GEN-LAST:event_roleJComboBoxActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox roleJComboBox;
    private javax.swing.JTable tblSecurityEmployees;
    // End of variables declaration//GEN-END:variables
}
