/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
*/
package UserInterface.ReceptionistRole;

import Business.Checks.CheckString;
import Business.EcoSystem;
import Business.Encryption.AESCrypt;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Organization.PatientOrganization;
import Business.Patient.Patient;
import Business.Person.Address;
import Business.Role.PatientRole;
import Business.Role.Role;
import Business.UserAccount.UserAccount;
import UserInterface.AdministrativeRole.ManageUserAccountJPanel;
import java.awt.CardLayout;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.apache.log4j.Logger;

/**
 *
 * @author Gauri
 */
public class AddPatientJPanel extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private PatientOrganization patientOrganization;
    private EcoSystem system;
    
    private static final Logger logger =Logger.getLogger(AddPatientJPanel.class);
    /**
     * Creates new form AddPatientJPanel
     */
    public AddPatientJPanel(JPanel userProcessContainer,Enterprise enterprise,EcoSystem system){//, PatientOrganization patientOrganization) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.enterprise=enterprise;
        this.system=system;
        
        populateCountryJComboBox();
    }
    public void populateCountryJComboBox(){
        countryJComboBox.removeAllItems();;
        
        countryJComboBox.addItem("USA");
        countryJComboBox.addItem("Canada");
        countryJComboBox.addItem("India");
        countryJComboBox.addItem("China");
    }
    
    public void clearFields(){
        txtUserName.setText("");
        txtName.setText("");
        txtLastName.setText("");
        txtPassword.setText("");
        txtStreetNo.setText("");
        txtCity.setText("");
        txtState.setText("");
        txtPinCode.setText("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAddPatient = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPatientId = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        txtPinCode = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtStreetNo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtState = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        countryJComboBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        jLabel13 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAddPatient.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnAddPatient.setText("Add Patient");
        btnAddPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPatientActionPerformed(evt);
            }
        });
        add(btnAddPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, 152, 43));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel2.setText("First Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, -1, -1));

        txtName.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 126, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel3.setText("Password");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, -1));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel5.setText("Patient Id");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, -1, -1));

        txtPatientId.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        txtPatientId.setEnabled(false);
        add(txtPatientId, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, 124, -1));

        btnBack.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, -1, -1));

        txtPinCode.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        add(txtPinCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 250, 126, 29));

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel6.setText("Street No.");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, -1, -1));

        txtStreetNo.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        add(txtStreetNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, 126, 29));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel7.setText("City");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, -1, -1));

        txtCity.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        add(txtCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 120, 126, 29));

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel8.setText("State");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, -1, -1));

        txtState.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        add(txtState, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 170, 126, 29));

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel9.setText("Country");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, -1, -1));

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel10.setText("Pincode");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, -1, -1));

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel11.setText("Last Name");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));

        txtLastName.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        add(txtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 126, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setText("Add Patient");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, -1));

        countryJComboBox.setFont(new java.awt.Font("Lucida Grande", 1, 11)); // NOI18N
        countryJComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        countryJComboBox.setMaximumSize(null);
        countryJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countryJComboBoxActionPerformed(evt);
            }
        });
        add(countryJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 210, 130, 29));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel4.setText("UserName");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, -1));

        txtUserName.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 126, -1));
        add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 130, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/4.png"))); // NOI18N
        jLabel13.setText("jLabel13");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPatientActionPerformed
        // TODO add your handling code here:
        String firstName=null;
        String lastName = null;
        String street = null;
        String city = null;
        String state = null;
        String country = null;
        int pinCode = 0;
        String userName=null;
        String password = null;
        
        
        try{
            firstName=txtName.getText().trim();
            lastName = txtLastName.getText();
            street = txtStreetNo.getText();
            city = txtCity.getText();
            state = txtState.getText();
            country = (String) countryJComboBox.getSelectedItem();
            pinCode = Integer.parseInt(txtPinCode.getText());
            userName=txtName.getText().trim();
           // password = txtPassword.getText().trim();
            char[] passwordArray = txtPassword.getPassword();
            password = String.valueOf(passwordArray);
            String encryptedPassword = null;
        
        try {
            encryptedPassword = AESCrypt.encrypt(password);
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(ManageUserAccountJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
            
            Organization org=null;
            for(Organization organization:enterprise.getOrganizationDirectory().getOrganizationList()){
                if(organization instanceof PatientOrganization){
                    org=organization;
                    break;
                }
            }
            
            if(org == null){
                JOptionPane.showMessageDialog(null, "First Create Patient Organization", "Information", JOptionPane.INFORMATION_MESSAGE);
            }
            
            if(org!=null){
                
                Boolean check = CheckString.stringValidation(firstName);
                Boolean check1 = CheckString.stringValidation(lastName);
                Boolean check2 = CheckString.stringValidation(city);
                Boolean check3 = CheckString.stringValidation(state);
                Boolean check5 = CheckString.IntValidation(pinCode); 
                Boolean check6 = CheckString.stringNumericValidation(street);
                Boolean checkUserName = CheckString.stringNumericValidation(userName);
                Boolean checkPassword = CheckString.stringNumericValidation(userName);
                
                if(check == true && check1==true && check2==true && check3==true && check5==true &&
                        check6==true && checkUserName==true &&checkPassword==true){
                    
                    Boolean checkSameUserName=false;
                    
                    for(Network n :system.getNetworkList()){
                        for(Enterprise e:n.getEnterpriseDirectory().getEnterpriseList()){
                            for(UserAccount ua:e.getUserAccountDirectory().getUserAccountList()){
                                
                                if(ua.getUserName().equalsIgnoreCase(userName)){
                                    checkSameUserName=true;
                                    break;
                                }
                            }
                        }
                    }
                    
                    if(!checkSameUserName){
                        Role patientRole= null;
                        for (Role role : org.getSupportedRole()){
                            if(role instanceof PatientRole){
                                patientRole=role;
                                break;
                            }
                        }
                        
                        Patient p = new Patient();
                        p.setId(system.getIv().getPersonId());
                        txtPatientId.setText(String.valueOf(p.getId()));
                        p.setFirstName(firstName);
                        p.setLastName(lastName);
                        Address a = new Address(street,city,state,country,pinCode);
                        p.setAddress(a);
                        org.getPersonDirectory().addPerson(p);
                        UserAccount ua =org.getUserAccountDirectory().createUserAccount(userName, encryptedPassword, p, patientRole, Boolean.TRUE);
                        if(ua==null){
                            
                        }
                        else{
                            logger.info("New Patient Created ! UserName : "+userName);
                            JOptionPane.showMessageDialog(null, "Patient Added Successfully !", "Information", JOptionPane.INFORMATION_MESSAGE);
                            populateCountryJComboBox();
                            clearFields();
                        }
                         
                    }else{
                        JOptionPane.showMessageDialog(null, "UserName Already Exists ! Enter Another UserName", "Warning", JOptionPane.WARNING_MESSAGE);
                        return;
                    }
                    
                    
                    
                }
            }
            
        }
        
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Enter correct data", "Warning", JOptionPane.WARNING_MESSAGE);
            
        }
        
        
        
        
    }//GEN-LAST:event_btnAddPatientActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void countryJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countryJComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_countryJComboBoxActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddPatient;
    private javax.swing.JButton btnBack;
    private javax.swing.JComboBox<String> countryJComboBox;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtPatientId;
    private javax.swing.JTextField txtPinCode;
    private javax.swing.JTextField txtState;
    private javax.swing.JTextField txtStreetNo;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
