/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
*/
package UserInterface.ReceptionistRole;

import Business.Enterprise.Enterprise;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.apache.log4j.Logger;

/**
 *
 * @author Gauri
 */
public class ViewProfileJPanel extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    
    private static final Logger logger =Logger.getLogger(ViewProfileJPanel.class);
    /**
     * Creates new form ViewPatientProfileJPanel
     */
    public ViewProfileJPanel(JPanel userProcessContainer,Enterprise enterprise,UserAccount userAccount) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.enterprise=enterprise;
        this.userAccount=userAccount;
        
        populateTextFields();
    }
    
    public void populateTextFields(){
        txtId.setText(String.valueOf(userAccount.getPerson().getId()));
        txtFirstName1.setText(userAccount.getPerson().getFirstName());
        txtLastName.setText(userAccount.getPerson().getLastName());
        txtUserName1.setText(userAccount.getUserName());
        txtIPAddress.setText(String.valueOf(userAccount.getPerson().getIPAddress()));
        txtStreetNo.setText(userAccount.getPerson().getAddress().getStreetNum());
        txtCity.setText(userAccount.getPerson().getAddress().getCity());
        txtState.setText(userAccount.getPerson().getAddress().getState());
        txtPinCode.setText(String.valueOf(userAccount.getPerson().getAddress().getPinCode()));
        txtCountry.setText(userAccount.getPerson().getAddress().getCountry());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCity = new javax.swing.JTextField();
        txtIPAddress = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtState = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtCountry = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtPinCode = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtStreetNo = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnChangePassword = new javax.swing.JButton();
        btnGo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPasswordBox = new javax.swing.JPasswordField();
        txtConfirmPasswordBox = new javax.swing.JPasswordField();
        txtFirstName1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtUserName1 = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCity.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        txtCity.setEnabled(false);
        add(txtCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 120, 126, -1));

        txtIPAddress.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        txtIPAddress.setEnabled(false);
        add(txtIPAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 140, -1));

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel8.setText("State");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, -1, -1));

        txtState.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        txtState.setEnabled(false);
        add(txtState, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 160, 126, -1));

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel9.setText("Country");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, -1, -1));

        txtCountry.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        txtCountry.setEnabled(false);
        add(txtCountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 200, 126, -1));

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel10.setText("Pincode");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 250, -1, -1));

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel11.setText("Last Name");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, -1, -1));

        txtPinCode.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        txtPinCode.setEnabled(false);
        add(txtPinCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 240, 126, -1));

        txtLastName.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        txtLastName.setEnabled(false);
        add(txtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 140, -1));

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel6.setText("Street No.");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, -1, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel2.setText("First Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, -1));

        txtStreetNo.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        txtStreetNo.setEnabled(false);
        add(txtStreetNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 80, 126, -1));

        txtId.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        txtId.setEnabled(false);
        add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 140, -1));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel7.setText("City");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel3.setText("UserName");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, -1, -1));

        btnChangePassword.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnChangePassword.setText("Reset Password");
        btnChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePasswordActionPerformed(evt);
            }
        });
        add(btnChangePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, -1, -1));

        btnGo.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnGo.setText("Go >>");
        btnGo.setEnabled(false);
        btnGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoActionPerformed(evt);
            }
        });
        add(btnGo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 480, -1, -1));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setText("Password");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 400, -1, -1));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel5.setText("Confirm Password");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 440, -1, -1));

        txtPasswordBox.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        txtPasswordBox.setEnabled(false);
        add(txtPasswordBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 390, 130, -1));

        txtConfirmPasswordBox.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        txtConfirmPasswordBox.setEnabled(false);
        txtConfirmPasswordBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConfirmPasswordBoxActionPerformed(evt);
            }
        });
        add(txtConfirmPasswordBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 430, 130, -1));

        txtFirstName1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        txtFirstName1.setEnabled(false);
        add(txtFirstName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 140, -1));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel4.setText("Id");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, -1));

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel12.setText("IP Address");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, -1, -1));

        txtUserName1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        txtUserName1.setEnabled(false);
        add(txtUserName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 140, -1));

        btnBack.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setText("Profile");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/4.png"))); // NOI18N
        jLabel14.setText("jLabel14");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePasswordActionPerformed
        // TODO add your handling code here:
        txtPasswordBox.setEnabled(true);
        txtConfirmPasswordBox.setEnabled(true);
        btnChangePassword.setEnabled(false);
        btnGo.setEnabled(true);
    }//GEN-LAST:event_btnChangePasswordActionPerformed

    private void btnGoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoActionPerformed
        // TODO add your handling code here:
        
        char[] passwordArray = txtPasswordBox.getPassword();
        String password = String.valueOf(passwordArray);
        
        char[] passwordArray1 = txtConfirmPasswordBox.getPassword();
        String password1 = String.valueOf(passwordArray1);
        
        if(password.equals(password1)){
            populateTextFields();
            userAccount.setPassword(password);
            logger.info(userAccount.getUserName()+" : of Role Type "+userAccount.getRole() +" Changed Password !");
            JOptionPane.showMessageDialog(null, "Password Changed Successfully !", "Information", JOptionPane.INFORMATION_MESSAGE);
            txtPasswordBox.setEnabled(false);
            txtConfirmPasswordBox.setEnabled(false);
            btnChangePassword.setEnabled(true);
            btnGo.setEnabled(false);
            txtPasswordBox.setText("");
            txtConfirmPasswordBox.setText("");
        }
        else{
            JOptionPane.showMessageDialog(null, "Passwords Do Not Match !", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        
    }//GEN-LAST:event_btnGoActionPerformed

    private void txtConfirmPasswordBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConfirmPasswordBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConfirmPasswordBoxActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnChangePassword;
    private javax.swing.JButton btnGo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtCity;
    private javax.swing.JPasswordField txtConfirmPasswordBox;
    private javax.swing.JTextField txtCountry;
    private javax.swing.JTextField txtFirstName1;
    private javax.swing.JTextField txtIPAddress;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JPasswordField txtPasswordBox;
    private javax.swing.JTextField txtPinCode;
    private javax.swing.JTextField txtState;
    private javax.swing.JTextField txtStreetNo;
    private javax.swing.JTextField txtUserName1;
    // End of variables declaration//GEN-END:variables
}
