/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Tier2Analyst;

import Business.Enterprise.Enterprise;
import Business.Organization.SecurityOrganization;
import Business.UserAccount.UserAccount;
import UserInterface.ReceptionistRole.ViewProfileJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;
import org.apache.log4j.Logger;

/**
 *
 * @author Gauri
 */
public class Tier2WorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private SecurityOrganization securityOrganization;
    private Enterprise enterprise;
    
    private static final Logger logger =Logger.getLogger(Tier2WorkAreaJPanel.class);
    /**
     * Creates new form Tier2WorkAreaJPanel
     */
    public Tier2WorkAreaJPanel(JPanel userProcessContainer, UserAccount userAccount, SecurityOrganization securityOrganization, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.userAccount=userAccount;
        this.securityOrganization=securityOrganization;
        this.enterprise=enterprise;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnViewPendingRequests = new javax.swing.JButton();
        btnCompletedRequests = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        btnViewProfile = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnViewPendingRequests.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnViewPendingRequests.setText("View Pending Requests");
        btnViewPendingRequests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewPendingRequestsActionPerformed(evt);
            }
        });
        add(btnViewPendingRequests, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 204, 55));

        btnCompletedRequests.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnCompletedRequests.setText("Completed Requests");
        btnCompletedRequests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompletedRequestsActionPerformed(evt);
            }
        });
        add(btnCompletedRequests, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 200, 55));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setText("Tier 2 Analyst Work Area");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, -1, -1));

        btnViewProfile.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnViewProfile.setText("View Profile");
        btnViewProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewProfileActionPerformed(evt);
            }
        });
        add(btnViewProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 480, 155, 49));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/4.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewPendingRequestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPendingRequestsActionPerformed
        // TODO add your handling code here:
        ViewWorkRequestsJPanel viewWorkRequestJPanel = new ViewWorkRequestsJPanel(userProcessContainer, userAccount, securityOrganization, enterprise);
        userProcessContainer.add("viewWorkRequestJPanel",viewWorkRequestJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewPendingRequestsActionPerformed

    private void btnCompletedRequestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompletedRequestsActionPerformed
        // TODO add your handling code here:
        ViewCompletedRequestsJPanel viewCompletedRequestJPanel = new ViewCompletedRequestsJPanel(userProcessContainer, userAccount, securityOrganization, enterprise);
        userProcessContainer.add("viewCompletedRequestJPanel",viewCompletedRequestJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnCompletedRequestsActionPerformed

    private void btnViewProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewProfileActionPerformed
        // TODO add your handling code here:
        logger.info(userAccount.getUserName()+" Viewed Profile");
        ViewProfileJPanel viewTier1AnalystProfileJPanel = new ViewProfileJPanel(userProcessContainer,enterprise,userAccount);
        userProcessContainer.add("viewTier1AnalystProfileJPanel",viewTier1AnalystProfileJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewProfileActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCompletedRequests;
    private javax.swing.JButton btnViewPendingRequests;
    private javax.swing.JButton btnViewProfile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    // End of variables declaration//GEN-END:variables
}
