/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Tier2Analyst;

import Business.Enterprise.Enterprise;
import Business.Organization.SecurityOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.UnusualActivityWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gauri
 */
public class ViewCompletedRequestsJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private SecurityOrganization securityOrganization;
    private Enterprise enterprise;
    /**
     * Creates new form ViewCompletedRequestsJPanel
     */
    public ViewCompletedRequestsJPanel(JPanel userProcessContainer, UserAccount userAccount, SecurityOrganization securityOrganization, Enterprise enterprise) {
        initComponents();
        
        this.userProcessContainer=userProcessContainer;
        this.userAccount=userAccount;
        this.securityOrganization=securityOrganization;
        this.enterprise=enterprise;
        
        populateWorkRequests();
    }
    
    public void populateWorkRequests(){
        DefaultTableModel dtm = (DefaultTableModel) tblCompletedRequests.getModel();
        dtm.setRowCount(0);
        
        for(WorkRequest request : userAccount.getWorkQueue().getWorkRequestList()){
            UnusualActivityWorkRequest unusualWorkRequest = (UnusualActivityWorkRequest) request;
            
            if(unusualWorkRequest.getStatus().equals("Action Performed by Tier2 Analyst")){
                Object row[]=new Object[6];
                row[0]=unusualWorkRequest;
                row[1]=unusualWorkRequest.getMessage();
                row[2]=unusualWorkRequest.getThreatUser().getUserName();
                row[3]=unusualWorkRequest.getSeverity();
                row[4]=unusualWorkRequest.getStatus();
                
                dtm.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCompletedRequests = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblCompletedRequests.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        tblCompletedRequests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblCompletedRequests);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 140, 589, 243));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setText("Completed Work Requests");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, -1, -1));

        btnBack.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/4.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCompletedRequests;
    // End of variables declaration//GEN-END:variables
}
